POST http://localhost:8080/meetings
Content-Type: application/json

{
    "leaders": ["domino"]
}

###
POST http://localhost:8080/meetings


###
GET http://localhost:8080/meetings


###
GET http://localhost:8080/meetings/5f315dbc590796a6cfa1de20


###
GET http://localhost:8080/ping


